### ISSUE TITLE
32bit binaries

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [zauonlok/renderer#10]
your win32 binaries are 64bit hehe

**Comment by zauonlok** [comment]
Yes, win32 is short for "Win32 API".

> Win32 is the programming interface (API) for 32-bit and 64-bit Windows operating systems. Starting with Windows 95, developers write applications that call the routines in the Win32 API.

[Definition of Win32 | PCMag](https://www.pcmag.com/encyclopedia/term/win32)

**Comment by MyTDT-Mysoft** [comment]
yeah i did understand that... despite using win32 api for a softrender have little sense other than the framebuffer, but still... the older version were 32bit so i had to ask, and anyway... without 32bit binaries, i can only try this if its possible to compile this with mingw64, so i will try

**Comment by pachuco** [comment]
Seconding x86 binaries request.

**Comment by pachuco** [comment]
In the meanwhile, here's a batch file that compiles using GCC.
https://gist.github.com/pachuco/43dcf77ea3b21c6b0ec3721a10153a25

I am pleasantly surprised by how easy this codebase is to compile.

**Comment by pachuco** [comment]
For shits and giggles, I fired up a windows 98SE VM and ran the viewer. It works!

**Comment by zauonlok** [comment]
> yeah i did understand that... despite using win32 api for a softrender have little sense other than the framebuffer, but still... the older version were 32bit so i had to ask, and anyway... without 32bit binaries, i can only try this if its possible to compile this with mingw64, so i will try

If you do not want to install Visual Studio, [Visual C++ Compiler for Python 2.7](https://web.archive.org/web/20210106040224/https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi) will also work (about 83M).

**Comment by zauonlok** [comment]
> For shits and giggles, I fired up a windows 98SE VM and ran the viewer. It works!

After all, the renderer is written in ANSI C.

**Comment by MyTDT-Mysoft** [comment]
yeah, nah compiled for mingw, since it was indeed easy, but most projects are not that easy to compile, so i tend to try them first to see if it worth the effort hehe

**Comment by zauonlok** [comment]
Yes, that is one of the benefits of minimal dependencies.
