### ISSUE TITLE
3d wireframe rendering?

### ISSUE THREAD

**Issue by starseeker** [zauonlok/renderer#3]
Hi!  I was wondering, is is possible (or planned) to be able to render wireframes in the scene?  Something along the lines of http://brlcad.org/gallery/picture.php?/96/category/12 ?

**Comment by zauonlok** [comment]
Wireframe rendering is possible. You can use the `draw2d_draw_line` function to do that.

https://github.com/zauonlok/renderer/blob/618f8d672188545272f747af3bbcbe2d7d51c7e7/renderer/core/draw2d.h#L10-L11 

This page describes the basic algorithm for line drawing and wireframe rendering: 

https://github.com/ssloy/tinyrenderer/wiki/Lesson-1-Bresenham%E2%80%99s-Line-Drawing-Algorithm#wireframe-rendering
